# Generated by Django 5.2.6 on 2025-09-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulances', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=200)),
                ('caller_phone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('at_scene', 'At Scene'), ('transporting', 'Transporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('request_source', models.CharField(choices=[('phone_call', 'Phone Call'), ('system', 'System'), ('mobile_app', 'Mobile App'), ('web_portal', 'Web Portal')], max_length=20)),
                ('requester_type', models.CharField(choices=[('individual', 'Individual'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('nursing_home', 'Nursing Home'), ('emergency_services', 'Emergency Services')], max_length=20)),
                ('requester_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.IntegerField(blank=True, help_text='Response time in minutes', null=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_calls', to='ambulances.ambulance')),
                ('dispatcher', models.ForeignKey(blank=True, limit_choices_to={'role': 'dispatcher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_calls', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_calls', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='ambulances.ambulance')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='dispatch.emergencycall')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
