# Generated by Django 5.2.6 on 2025-09-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('at_scene', 'At Scene'), ('transporting', 'Transporting'), ('at_hospital', 'At Hospital'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('equipment', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_ambulances', to=settings.AUTH_USER_MODEL)),
                ('assigned_paramedic', models.ForeignKey(blank=True, limit_choices_to={'role': 'paramedic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paramedic_ambulances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
    ]
